name: Deploy Salesforce Metadata

on:
  push:
    branches:
      - main # Or your main branch
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for calculating changes

      - name: Install Salesforce CLI
        run: |
          npm install -g sfdx-cli@latest

      - name: Authenticate with Salesforce
        run: |
          sfdx auth:sfdxurl:store -f ./connection.txt
      - name: Create Connection File
        run: |
          echo "SFDX_URL=sfdx://{(
            'type':'WEB', \
            'url':'${{ env.SF_URL }}', \
            'username':'${{ secrets.SF_USERNAME }}', \
            'password':'${{ secrets.SF_PASSWORD }}'\
          )}" > connection.txt
      - name: Deploy Metadata
        run: |
          sfdx force:source:deploy --manifest=./manifest/package.xml --target-org=sfdx-url.json --wait=10 --verbose

      - name: Run destructive changes (if applicable)
        if: ${{ github.event_name == 'push' }}
        run: |
          # Example: Deploy destructive changes if a destructiveChanges.xml exists
          if [ -f "./manifest/destructiveChanges.xml" ]; then
            sfdx force:source:deploy --manifest=./manifest/destructiveChanges.xml --target-org=sfdx-url.json --wait=10 --verbose
          fi
